### ISSUE TITLE
Could not execute GraphicsMagick/ImageMagick

### ISSUE THREAD

**Issue by SlimMarten** [selaux/node-sprite-generator#52]
Hi, I was just trying to run the generator but I get the following error:

> Error: Could not execute GraphicsMagick/ImageMagick: gm "identify" "-ping" "-format" "%wx%h" "-" this most likely means the gm/convert binaries can't be found
>     at ChildProcess.<anonymous> (/[PROJECT]/node_modules/gm/lib/command.js:231:12)
>     at emitOne (events.js:96:13)
>     at ChildProcess.emit (events.js:188:7)
>     at Process.ChildProcess._handle.onexit (internal/child_process.js:213:12)
>     at onErrorNT (internal/child_process.js:359:16)
>     at _combinedTickCallback (internal/process/next_tick.js:74:11)
>     at process._tickCallback (internal/process/next_tick.js:98:9)

**Comment by SlimMarten** [comment]
I missed the part where it says that imagemagick is required, sorry for that.
