### ISSUE TITLE
Error installing node-sprite-generator

### ISSUE THREAD

**Issue by explorer2309** [selaux/node-sprite-generator#79]
I am running Windows 10, Node 10.16.2

On running `npm install node-sprite-generator`, I get this error:

```
gyp ERR! configure error
gyp ERR! stack Error: Command failed: C:\Python361\python.EXE -c import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack   File "<string>", line 1
gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack                                ^
gyp ERR! stack SyntaxError: invalid syntax
gyp ERR! stack
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:294:12)
gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
gyp ERR! stack     at maybeClose (internal/child_process.js:982:16)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
gyp ERR! System Windows_NT 10.0.17763
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\t965267\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Delia\node-sprite-gen\node_modules\canvas
gyp ERR! node -v v10.16.2
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok

```

Do I need some other version of python on my machine?

**Comment by selaux** [comment]
AFAIK node-gyp still requires python2.
